name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: branch names
      - run: echo "${{github.base_ref}} and ${{github.head_ref}}"
