name: Close Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: branch names
        run: echo "${{github.base_ref}} and ${{github.head_ref}}"
      - name: running script
        uses: actions/github-script@v6
        id: set-result
        with:
         script: |
              return branches('${{github.head_ref}}', '${{github.base_ref}}')
              function branches(head, base){
                if(base==='Manideepakakula-patch-1'){
                    return true }
                else {return false}
                }
         result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      #const value = require('./branch-nomenclature.js')
      #await value('${{github.base_ref}}', '${{github.head_ref}}')
      - name: closing pr
        if: ${{steps.set-result.outputs.result== 'false'}}
        uses: superbrothers/close-pull-request@v3
        with:
         comment: "branch rules were violated"
