name: Close Pull Request

on:
  push

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      value: ${{steps.v.outputs.result}}
    steps:
      - name: first one
        id: v
        uses: actions/github-script@v6
        with:
          script: |
            const obj= {
            a: "one",
            b: "two"
            }
            console.log(obj)
            return obj
  second-run: 
    runs-on: ubuntu-latest
    steps:
      - name: second one
        run: |
          echo "${{ fromJSON(needs.run.outputs.value) }}"
          echo "${{ fromJSON(needs.run.outputs.value).a }}"
