name: Close Pull Request

on:
  pull_request_target:
    #types: [opened, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: branch names
      - run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      - name: print branches
      - run: echo "branches sre $BRANCH_NAME and"
      #sdf
      #other commits
      #asfSggs
      
