name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: branch names
      - run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
      - run: echo "::set-env name=BRANCH_NAME2::$(echo ${GITHUB_BASE_REF})"
      - name: print branches
      - run: echo "branches sre $BRANCH_NAME and $BRANCH_NAME2"
      #sdf
      
