name: Close Pull Request

on:
  pull_request_target:
    #types: [opened, synchronize, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: branch names
        run: echo "${{GITHUB_HEAD_REF}}"
        #dfshft
